"""empty message

Revision ID: 727f7b08f766
Revises: f49c137f30dd
Create Date: 2026-09-24 19:43:10.342864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '727f7b08f766'
down_revision: Union[str, Sequence[str], None] = 'f49c137f30dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_lesson_titles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('lesson_title_id', sa.String(length=256), nullable=False),
    sa.Column('lesson_title_index', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint('lesson_title_index BETWEEN 0 AND 1', name='ck_lesson_lesson_titles_lesson_title_index'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_title_id'], ['lesson_titles.index'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lesson_lesson_titles_lesson_id_lesson_title_id', 'lesson_lesson_titles', ['lesson_id', 'lesson_title_id'], unique=False)
    op.drop_constraint(op.f('lessons_name_id_fkey'), 'lessons', type_='foreignkey')
    op.drop_column('lessons', 'name_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('name_id', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('lessons_name_id_fkey'), 'lessons', 'lesson_titles', ['name_id'], ['index'], ondelete='RESTRICT')
    op.drop_index('idx_lesson_lesson_titles_lesson_id_lesson_title_id', table_name='lesson_lesson_titles')
    op.drop_table('lesson_lesson_titles')
    # ### end Alembic commands ###
