"""empty message

Revision ID: f49c137f30dd
Revises:
Create Date: 2026-09-20 20:13:12.105487

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f49c137f30dd"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.create_table(
        "bot_users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "joined_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_activity_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_bot_users_user_id"), "bot_users", ["user_id"], unique=False
    )
    op.create_table(
        "cabinets",
        sa.Column("index", sa.String(length=32), nullable=False),
        sa.Column("number", sa.String(length=48), nullable=False),
        sa.PrimaryKeyConstraint("index"),
    )
    op.create_table(
        "groups",
        sa.Column("index", sa.String(length=6), nullable=False),
        sa.Column("number", sa.String(length=7), nullable=False),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.PrimaryKeyConstraint("index"),
    )
    op.create_table(
        "lesson_times",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("time_type", sa.String(length=24), nullable=False),
        sa.Column("lesson_start", sa.Time(), nullable=False),
        sa.Column("lesson_end", sa.Time(), nullable=False),
        sa.Column(
            "active_from",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("active_until", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "time_type IN ('standard', 'reduced')", name="ck_lesson_times_time_type"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_lesson_times_time_type_lesson_start",
        "lesson_times",
        ["time_type", "lesson_start"],
        unique=True,
        postgresql_where="active_until IS NULL",
    )
    op.create_table(
        "lesson_titles",
        sa.Column("index", sa.String(length=256), nullable=False),
        sa.Column("original_title", sa.String(length=256), nullable=False),
        sa.Column("custom_title", sa.String(length=256), nullable=True),
        sa.Column(
            "is_countable", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.PrimaryKeyConstraint("index"),
    )
    op.create_index(
        "idx_lesson_titles_effective_title_trgm",
        "lesson_titles",
        [sa.literal_column("COALESCE(custom_title, original_title) gin_trgm_ops")],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"coalesce": "gin_trgm_ops"},
    )
    op.create_table(
        "bot_user_cabinet_subscribes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("cabinet_index", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["cabinet_index"], ["cabinets.index"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["bot_users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_bot_user_cabinet_subscribes_user_id_cabinet_index",
        "bot_user_cabinet_subscribes",
        ["user_id", "cabinet_index"],
        unique=True,
    )
    op.create_table(
        "bot_user_group_subscribes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("group_index", sa.String(length=6), nullable=False),
        sa.ForeignKeyConstraint(["group_index"], ["groups.index"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["bot_users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_bot_user_group_subscribes_user_id_group_index",
        "bot_user_group_subscribes",
        ["user_id", "group_index"],
        unique=True,
    )
    op.create_table(
        "bot_users_metadata",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["bot_users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_bot_users_metadata_user_id_key",
        "bot_users_metadata",
        ["user_id", "key"],
        unique=True,
    )
    op.create_table(
        "cabinet_redirects",
        sa.Column("cabinet_from_index", sa.String(length=32), nullable=False),
        sa.Column("cabinet_to_index", sa.String(length=32), nullable=False),
        sa.CheckConstraint(
            "cabinet_from_index != cabinet_to_index",
            name="ck_cabinet_redirects_no_self",
        ),
        sa.ForeignKeyConstraint(
            ["cabinet_from_index"], ["cabinets.index"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["cabinet_to_index"], ["cabinets.index"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("cabinet_from_index"),
    )
    op.create_table(
        "lesson_title_redirects",
        sa.Column("title_from_index", sa.String(length=256), nullable=False),
        sa.Column("title_to_index", sa.String(length=256), nullable=False),
        sa.CheckConstraint(
            "title_from_index != title_to_index",
            name="ck_lesson_title_redirects_no_self",
        ),
        sa.ForeignKeyConstraint(
            ["title_from_index"], ["lesson_titles.index"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["title_to_index"], ["lesson_titles.index"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("title_from_index"),
    )
    op.create_table(
        "lessons",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("lesson_at", sa.Date(), nullable=False),
        sa.Column("group_index", sa.String(length=6), nullable=False),
        sa.Column("time_range_id", sa.Integer(), nullable=False),
        sa.Column("name_id", sa.String(length=256), nullable=False),
        sa.ForeignKeyConstraint(["group_index"], ["groups.index"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["name_id"], ["lesson_titles.index"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["time_range_id"], ["lesson_times.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_lessons_lesson_at_group_index",
        "lessons",
        ["group_index", "lesson_at"],
        unique=False,
    )
    op.create_table(
        "lesson_cabinets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("lesson_id", sa.Integer(), nullable=False),
        sa.Column("cabinet_id", sa.String(length=32), nullable=False),
        sa.Column("cabinet_index", sa.SmallInteger(), nullable=False),
        sa.CheckConstraint(
            "cabinet_index BETWEEN 0 AND 1", name="ck_lesson_cabinets_cabinet_index"
        ),
        sa.ForeignKeyConstraint(
            ["cabinet_id"], ["cabinets.index"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["lesson_id"], ["lessons.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_lesson_cabinets_lesson_id_cabinet_id",
        "lesson_cabinets",
        ["lesson_id", "cabinet_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_lesson_cabinets_lesson_id_cabinet_id", table_name="lesson_cabinets"
    )
    op.drop_table("lesson_cabinets")
    op.drop_index("idx_lessons_lesson_at_group_index", table_name="lessons")
    op.drop_table("lessons")
    op.drop_table("lesson_title_redirects")
    op.drop_table("cabinet_redirects")
    op.drop_index("idx_bot_users_metadata_user_id_key", table_name="bot_users_metadata")
    op.drop_table("bot_users_metadata")
    op.drop_index(
        "idx_bot_user_group_subscribes_user_id_group_index",
        table_name="bot_user_group_subscribes",
    )
    op.drop_table("bot_user_group_subscribes")
    op.drop_index(
        "idx_bot_user_cabinet_subscribes_user_id_cabinet_index",
        table_name="bot_user_cabinet_subscribes",
    )
    op.drop_table("bot_user_cabinet_subscribes")
    op.drop_index(
        "idx_lesson_titles_effective_title_trgm",
        table_name="lesson_titles",
        postgresql_using="gin",
        postgresql_ops={"coalesce": "gin_trgm_ops"},
    )
    op.drop_table("lesson_titles")
    op.drop_index(
        "idx_lesson_times_time_type_lesson_start",
        table_name="lesson_times",
        postgresql_where="active_until IS NULL",
    )
    op.drop_table("lesson_times")
    op.drop_table("groups")
    op.drop_table("cabinets")
    op.drop_index(op.f("ix_bot_users_user_id"), table_name="bot_users")
    op.drop_table("bot_users")
    op.execute("DROP EXTENSION IF EXISTS pg_trgm")
    # ### end Alembic commands ###
